CreateConVar("ttt_iWin1", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Lion Sleeps Tonight - The Tokens")
CreateConVar("ttt_iWin2", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Come and Get your Love - Redbone")
CreateConVar("ttt_iWin3", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Horn of Plenty - James Newton Howard")
CreateConVar("ttt_iWin4", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Captain Jack - Captain Jack")
CreateConVar("ttt_iWin5", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Venice Rooftops Variation - Jesper Kyd")
CreateConVar("ttt_iWin6", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Numa Numa Yei - O-zone")
CreateConVar("ttt_iWin7", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Dovahkiin - Lindsey Stirling&Peter Hollens")
CreateConVar("ttt_iWin8", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Hanging Tree - James Newton Howard")
CreateConVar("ttt_iWin9", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "1812 Overture - Tchaikovsky")
CreateConVar("ttt_iWin10", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Ghostbusters - Spooky")
CreateConVar("ttt_iWin11", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Chip&Chap (German) - Mark Müller")
CreateConVar("ttt_iWin12", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Hüpfen hier und dort und überall - Patty Silversher")
CreateConVar("ttt_iWin13", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Duck Tales (German) - Mr.Tac")
CreateConVar("ttt_iWin14", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Sexy and I know It - LMFAO")
CreateConVar("ttt_iWin15", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Success - Monster Hunter Tri")
CreateConVar("ttt_iWin16", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Diggy Hole - The Yogscast")
CreateConVar("ttt_iWin17", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Leb deinen Traum - Frank Schindel")
CreateConVar("ttt_iWin18", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Barbie Girl - Aqua")
CreateConVar("ttt_iWin19", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Cotton Eye Joe - Rednex")
CreateConVar("ttt_iWin20", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Sag das Zauberwort - Andy Knote&Tina Hierstetter")
CreateConVar("ttt_iWin21", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Dubi Dam Dam - Banaroo")
CreateConVar("ttt_iWin22", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Sweet Victory 2-UPPM - Bob Kulick&David Eisley")
CreateConVar("ttt_iWin23", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Get Knocked Down - Chumbawamba")
CreateConVar("ttt_iWin24", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Blues Clues - Blues Clues")
CreateConVar("ttt_iWin25", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Chip&Dale (English) - Mark Müller")
CreateConVar("ttt_iWin26", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Duck Tales (English) - Mr.Tac")
CreateConVar("ttt_iWin27", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Bouncing here and there and everywhere - Patty Silversher")
CreateConVar("ttt_iWin28", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Traitor - Daughtry")

CreateConVar("ttt_traWin1", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Make it Bun Dem - Skrillex&Damian Marley")
CreateConVar("ttt_traWin2", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Where the Hood - DMX")
CreateConVar("ttt_traWin3", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Highway to Hell - ACDC")
CreateConVar("ttt_traWin4", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Right Round - Flo Rida")
CreateConVar("ttt_traWin5", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Reborn - League of Legends")
CreateConVar("ttt_traWin6", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "The Imperial March - John Williams")
CreateConVar("ttt_traWin7", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "You are a Pirate - Lazy Town")
CreateConVar("ttt_traWin8", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Fabulous Secret Powers SLACKCiRCUS")
CreateConVar("ttt_traWin9", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "We Are Number One - Lazy Town")
CreateConVar("ttt_traWin10", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "NeinNeinNein - Dupskoification")
CreateConVar("ttt_traWin11", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "What Does The Fox Say - Ylvis")
CreateConVar("ttt_traWin12", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Gangnam Style - PSY")
CreateConVar("ttt_traWin13", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Crazy Frog - Axel F")
CreateConVar("ttt_traWin14", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Piratentanz - Willi Girmes")
CreateConVar("ttt_traWin15", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Team Rocket - Pokemon")
CreateConVar("ttt_traWin16", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "BlaBlaBla - Gigi DAgostino")
CreateConVar("ttt_traWin17", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Jizz - Figrin D'an and the Modal Nodes")
CreateConVar("ttt_traWin18", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Cacion delirio de estadio - Spongebob")
CreateConVar("ttt_traWin19", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Ooh Eeh Uuh Ah Aah Ting Tang Walla Walla Bing - Witch Doctor")
CreateConVar("ttt_traWin20", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Peace Walker - Metal Gear Solid")
CreateConVar("ttt_traWin21", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "O Fortuna ~ Carmina Burana - Carl Orff")
CreateConVar("ttt_traWin22", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Hellmarch - Frank Klepacki")
CreateConVar("ttt_traWin23", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Jojo's Bizarre Adventure - Awaken Pillar Men")

CreateConVar("ttt_tOut1", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "CHA-LA HEAD-CHA-LA - Hironobu Kageyama")
CreateConVar("ttt_tOut2", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Heart of Courage - Two Steps From Hell")
CreateConVar("ttt_tOut3", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Let's do the timewarp again - E.A. Smith")
CreateConVar("ttt_tOut4", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "The Game Is On - David Arnold&Michael Price")
CreateConVar("ttt_tOut5", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Rollin' - Limp Bizkit")
CreateConVar("ttt_tOut6", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Tex Avery Show (German) - Mike Piccirillo")
CreateConVar("ttt_tOut7", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Quest failed - Monster Hunter Tri")
CreateConVar("ttt_tOut8", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "BennyHillTheme - James Rich&Randolph Boots&Leslie Mark Hill")
CreateConVar("ttt_tOut9", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Wer hat an der Uhr gedreht - Eric Frantzen")
CreateConVar("ttt_tOut10", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "Tex Avery Show(English) - Mike Piccirillo")
CreateConVar("ttt_tOut11", "1", {FCVAR_REPLICATED, FCVAR_ARCHIVE, FCVAR_NOTIFY, FCVAR_SERVER_CAN_EXECUTE}, "CHA-LA HEAD-CHA-LA(English) - Hironobu Kageyama")
